version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: {  interval: "daily" }
    labels: [ "area-deps", "area-automation" ]
    reviewers: [ "rdeago" ]
  - package-ecosystem: "nuget"
    directory: "/"
    schedule: {  interval: "daily" }
    labels: [ "area-deps" ]
    reviewers: [ "rdeago" ]
